name = "Run"
version = "0.1.0"
defaultTargets = ["Run"]

# [[lean_exe]]
# name = "Main"
# root = "Run"

[[lean_lib]]
name = "Run"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"

# [[require]]
# name = "mathlib"
# path = "C:/Users/Lean/mathlib4"