name = "project"
version = "0.1.0"
defaultTargets = ["project"]

# [[lean_exe]]
# name = "project"
# root = "Main"

[[lean_lib]]
name = "project"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"

# [[require]]
# name = "mathlib"
# path = "C:/Users/Lean/mathlib4"